import type { MissionTemplate } from "./types";
import {
  generateEqualShare,
  generateFractionSubtract,
  generateBudgetSubtract,
  generateUnitConvert,
  generateMissingAngle,
  generateDataTotal,
  generateTimeDuration,
  generatePatternMissing,
  generateMultiply,
  generateFractionAdd,
  generatePerimeter,
  generateMissingFactor,
  generateMultiStepBudgetDiscount,
  generateMultiStepFractionScale,
  generateMultiStepUnitSubtract,
} from "./missionMath";
import type { BudgetItem, DataCategory } from "./missionMath";

/**
 * Mission content — the story/theme layer, same role `lib/content/topics.ts`
 * plays for lesson content: plain data, not generated at request time.
 * The MATH is randomized per play (via each variant's `generateMath`);
 * the STORY VARIANT is also randomized per play (one of `variants` picked
 * at random) — together those satisfy the "same concept, different story"
 * requirement without needing a live AI call for core gameplay.
 *
 * This is a first, real vertical slice: the 3 example missions from the
 * brief, fully built end to end (engine + content + UI). Extending to the
 * other 6 categories (measurement, geometry, data, time, kbat, real_life)
 * and adding more missions per category is pure content work from here —
 * new MissionTemplate entries, no engine changes needed. See HANDOVER.md.
 */

const GROCERY_ITEMS: BudgetItem[] = [
  { name: { ms: "Roti", en: "Bread" }, priceRM: 4 },
  { name: { ms: "Susu", en: "Milk" }, priceRM: 8 },
  { name: { ms: "Beras", en: "Rice" }, priceRM: 22 },
  { name: { ms: "Telur", en: "Eggs" }, priceRM: 7 },
  { name: { ms: "Gula", en: "Sugar" }, priceRM: 5 },
  { name: { ms: "Sayur", en: "Vegetables" }, priceRM: 9 },
];

const CAMPING_ITEMS: BudgetItem[] = [
  { name: { ms: "Khemah", en: "Tent" }, priceRM: 25 },
  { name: { ms: "Lampu suluh", en: "Flashlight" }, priceRM: 6 },
  { name: { ms: "Beg tidur", en: "Sleeping bag" }, priceRM: 18 },
  { name: { ms: "Set makanan", en: "Food set" }, priceRM: 12 },
  { name: { ms: "Tali", en: "Rope" }, priceRM: 4 },
];

const FRUIT_CATEGORIES: DataCategory[] = [
  { name: { ms: "Epal", en: "Apples" } },
  { name: { ms: "Mangga", en: "Mangoes" } },
  { name: { ms: "Pisang", en: "Bananas" } },
  { name: { ms: "Oren", en: "Oranges" } },
  { name: { ms: "Tembikai", en: "Watermelons" } },
];

const TOY_MARKET_ITEMS: BudgetItem[] = [
  { name: { ms: "Bola", en: "Ball" }, priceRM: 6 },
  { name: { ms: "Buku cerita", en: "Storybook" }, priceRM: 9 },
  { name: { ms: "Blok binaan", en: "Building blocks" }, priceRM: 15 },
  { name: { ms: "Kereta mainan", en: "Toy car" }, priceRM: 7 },
  { name: { ms: "Puzzle", en: "Puzzle" }, priceRM: 11 },
];

const WEATHER_CATEGORIES: DataCategory[] = [
  { name: { ms: "Hari Cerah", en: "Sunny days" } },
  { name: { ms: "Hari Hujan", en: "Rainy days" } },
  { name: { ms: "Hari Berawan", en: "Cloudy days" } },
  { name: { ms: "Hari Berangin", en: "Windy days" } },
];

const HOUSEHOLD_BILLS: BudgetItem[] = [
  { name: { ms: "Bil elektrik", en: "Electricity bill" }, priceRM: 45 },
  { name: { ms: "Bil air", en: "Water bill" }, priceRM: 18 },
  { name: { ms: "Bil internet", en: "Internet bill" }, priceRM: 30 },
  { name: { ms: "Bil telefon", en: "Phone bill" }, priceRM: 25 },
];

const MERCHANT_GOODS: BudgetItem[] = [
  { name: { ms: "Kain sutera", en: "Silk cloth" }, priceRM: 24 },
  { name: { ms: "Rempah", en: "Spices" }, priceRM: 14 },
  { name: { ms: "Guni beras", en: "Rice sack" }, priceRM: 18 },
  { name: { ms: "Balang madu", en: "Honey jar" }, priceRM: 9 },
  { name: { ms: "Bakul buah", en: "Fruit basket" }, priceRM: 15 },
];

export const MISSIONS: MissionTemplate[] = [
  {
    id: "lost-kittens",
    category: "number",
    kind: "rescue",
    yearLevel: 4,
    title: { ms: "Anak Kucing Yang Hilang", en: "The Lost Kittens" },
    skillTag: { ms: "Bahagi & agihan sama rata", en: "Division & equal sharing" },
    emoji: "🐱",
    rewardXp: 20,
    badgeId: "kindness",
    variants: [
      {
        image: "/missions/scenes/lost-kittens-0.webp",
        tokens: {
          character: { ms: "anak kucing", en: "kittens" },
          item: { ms: "susu", en: "milk" },
          place: { ms: "Hutan Nombor", en: "Number Forest" },
        },
        intro: {
          ms: "Pintar sedang berjalan melalui {place} apabila dia terdengar bunyi mengiau yang lembut. Beberapa {character} yang ditinggalkan sedang bersembunyi di belakang semak.",
          en: "Pintar is walking through {place} when he hears tiny meows. Some abandoned {character} are hiding behind a bush.",
        },
        challenge: {
          ms: "{character} itu perlu menerima {item} sama banyak setiap seekor. Bolehkah anda bantu Pintar agihkannya sama rata?",
          en: "The {character} should each receive an equal amount of {item}. Can you help Pintar share it out equally?",
        },
        outcomeSuccess: {
          ms: "{character} itu gembira minum {item} mereka. Terima kasih kerana membantu!",
          en: "The {character} happily drink their {item}. Thanks for helping!",
        },
        outcomeRetry: {
          ms: "Belum tepat lagi — {character} itu masih menunggu bahagian yang sama rata. Cuba kira semula.",
          en: "Not quite yet — the {character} are still waiting for an equal share. Try the calculation again.",
        },
        reflection: {
          ms: "Anda baru sahaja guna PEMBAHAGIAN untuk agihkan sesuatu sama rata — kemahiran yang sama digunakan setiap kali sesuatu perlu dikongsi secara adil!",
          en: "You just used DIVISION to share something equally — the same skill you'd use any time something needs to be split fairly!",
        },
        generateMath: (mode) => generateEqualShare([5, 4, 8], mode),
      },
      {
        image: "/missions/scenes/lost-kittens-1.webp",
        tokens: {
          character: { ms: "anak anjing", en: "puppies" },
          item: { ms: "makanan", en: "food" },
          place: { ms: "Ladang Bahagi", en: "Division Farm" },
        },
        intro: {
          ms: "Di {place}, Pintar menjumpai sekumpulan {character} kecil yang lapar, menunggu waktu makan.",
          en: "At {place}, Pintar finds a litter of hungry {character}, waiting for feeding time.",
        },
        challenge: {
          ms: "{character} itu perlu menerima {item} sama banyak setiap seekor supaya semua kenyang.",
          en: "The {character} need to receive an equal amount of {item} each so everyone gets enough.",
        },
        outcomeSuccess: {
          ms: "Semua {character} makan dengan gembira — agihan yang adil untuk semua!",
          en: "All the {character} eat happily — a fair share for everyone!",
        },
        outcomeRetry: {
          ms: "Cuba semak semula — setiap {character} patut dapat bahagian yang SAMA.",
          en: "Check again — each of the {character} should get the SAME share.",
        },
        reflection: {
          ms: "PEMBAHAGIAN membantu kita agihkan sesuatu secara adil, walaupun jumlahnya tidak genap.",
          en: "DIVISION helps us share things fairly, even when the total doesn't divide into whole numbers.",
        },
        generateMath: (mode) => generateEqualShare([4, 5, 10], mode),
      },
      {
        image: "/missions/scenes/lost-kittens-2.webp",
        tokens: {
          character: { ms: "burung kecil", en: "birds" },
          item: { ms: "bijirin", en: "seeds" },
          place: { ms: "Taman Burung", en: "Bird Garden" },
        },
        intro: {
          ms: "Sekumpulan {character} mendarat di {place}, mencari makanan untuk sarapan pagi.",
          en: "A flock of {character} lands in the {place}, looking for breakfast.",
        },
        challenge: {
          ms: "Pintar ada sedikit {item} untuk diagihkan sama rata kepada setiap {character}.",
          en: "Pintar has a small amount of {item} to share equally among the {character}.",
        },
        outcomeSuccess: {
          ms: "Setiap {character} mematuk bahagian mereka dengan gembira!",
          en: "Each of the {character} happily pecks at their share!",
        },
        outcomeRetry: {
          ms: "Belum tepat — cuba bahagikan semula supaya setiap {character} dapat jumlah yang sama.",
          en: "Not quite — try dividing again so every one of the {character} gets the same amount.",
        },
        reflection: {
          ms: "Berkongsi sama rata itu PEMBAHAGIAN — kemahiran yang berguna setiap hari!",
          en: "Sharing equally is DIVISION — a skill that's useful every single day!",
        },
        generateMath: (mode) => generateEqualShare([2, 8, 10], mode),
      },
    ],
  },
  {
    id: "bridge-to-fraction-valley",
    category: "fraction",
    kind: "builder",
    yearLevel: 5,
    title: { ms: "Jambatan ke Lembah Pecahan", en: "Bridge to Fraction Valley" },
    skillTag: { ms: "Tolak pecahan (penyebut sama)", en: "Fraction subtraction (same denominator)" },
    emoji: "🌉",
    rewardXp: 25,
    badgeId: "bridge_builder",
    variants: [
      {
        image: "/missions/scenes/bridge-to-fraction-valley-0.webp",
        tokens: { material: { ms: "tali", en: "rope" }, place: { ms: "Lembah Pecahan", en: "Fraction Valley" } },
        intro: { ms: "Sebuah jambatan kayu di {place} telah runtuh. Pintar perlu membaikinya sebelum senja.", en: "A wooden bridge in {place} has collapsed. Pintar needs to fix it before nightfall." },
        challenge: { ms: "Untuk membaikinya, Pintar perlukan sepanjang {material} tertentu. Dia sudah ada sebahagian daripadanya.", en: "To rebuild it, Pintar needs a certain length of {material}. He already has part of it." },
        outcomeSuccess: { ms: "Jambatan itu berjaya dibaiki! {place} kini boleh diterokai.", en: "The bridge is repaired! {place} is now unlocked." },
        outcomeRetry: { ms: "{material} itu masih tidak cukup panjang — cuba kira semula berapa lagi yang diperlukan.", en: "The {material} still isn't long enough — try the calculation again." },
        reflection: { ms: "Anda baru sahaja TOLAK dua pecahan berpenyebut sama — cara yang sama digunakan setiap kali kita bandingkan dua bahagian!", en: "You just SUBTRACTED two fractions with the same denominator — the same method used any time we compare two parts!" },
        generateMath: (mode) => generateFractionSubtract([4, 8], mode),
      },
      {
        image: "/missions/scenes/bridge-to-fraction-valley-1.webp",
        tokens: { material: { ms: "papan", en: "planks" }, place: { ms: "Kampung Pecahan", en: "Fraction Village" } },
        intro: { ms: "Sebuah laluan kayu menuju {place} telah reput dan perlu dibaiki segera.", en: "A wooden path leading to {place} has rotted and needs urgent repair." },
        challenge: { ms: "Pintar perlukan sejumlah {material} tertentu untuk siapkan laluan itu.", en: "Pintar needs a certain amount of {material} to finish the path." },
        outcomeSuccess: { ms: "Laluan itu selesai dibaiki — perjalanan ke {place} kini selamat!", en: "The path is repaired — the way to {place} is now safe!" },
        outcomeRetry: { ms: "Masih belum cukup {material} — semak semula pengiraan pecahan anda.", en: "Still not enough {material} — double-check your fraction calculation." },
        reflection: { ms: "Menolak pecahan membantu kita cari BERAPA LAGI yang diperlukan.", en: "Subtracting fractions helps us find HOW MUCH MORE is needed." },
        generateMath: (mode) => generateFractionSubtract([5, 6, 10], mode),
      },
      {
        image: "/missions/scenes/bridge-to-fraction-valley-2.webp",
        tokens: { material: { ms: "kain layar", en: "sailcloth" }, place: { ms: "Pulau Pecahan", en: "Fraction Island" } },
        intro: { ms: "Layar sebuah perahu kecil menuju {place} telah koyak separuh jalan.", en: "The sail of a small boat heading to {place} has torn halfway through the journey." },
        challenge: { ms: "Pintar perlu menampal layar itu dengan sejumlah {material} tertentu.", en: "Pintar needs to patch the sail with a certain amount of {material}." },
        outcomeSuccess: { ms: "Layar telah ditampal — perahu itu boleh belayar ke {place}!", en: "The sail is patched — the boat can sail on to {place}!" },
        outcomeRetry: { ms: "Tampalan itu masih tidak cukup besar — cuba kira semula.", en: "The patch still isn't big enough — try recalculating." },
        reflection: { ms: "Menolak pecahan berpenyebut sama bermakna kita tolak sahaja PENGANGKA — penyebut kekal sama.", en: "Subtracting same-denominator fractions means we just subtract the NUMERATORS — the denominator stays the same." },
        generateMath: (mode) => generateFractionSubtract([4, 5, 12], mode),
      },
    ],
  },
  {
    id: "grocery-challenge",
    category: "money",
    kind: "financial_literacy",
    yearLevel: 4,
    title: { ms: "Cabaran Membeli-belah", en: "Grocery Challenge" },
    skillTag: { ms: "Wang & tolak berbilang item", en: "Money & multi-item subtraction" },
    emoji: "🛒",
    rewardXp: 30,
    badgeId: "money_hero",
    variants: [
      {
        image: "/missions/scenes/grocery-challenge-0.webp",
        tokens: { helper: { ms: "seorang nenek", en: "a grandmother" }, place: { ms: "pasar", en: "the market" } },
        intro: { ms: "Pintar membantu {helper} membeli-belah di {place}.", en: "Pintar helps {helper} do her shopping at {place}." },
        challenge: { ms: "Selepas semua barangan dibeli, berapakah baki wang yang tinggal?", en: "After all the items are bought, how much money is left?" },
        outcomeSuccess: { ms: "{helper} berjaya selesaikan belian dengan bajet yang mencukupi!", en: "{helper} successfully completes her shopping within budget!" },
        outcomeRetry: { ms: "Cuba kira semula jumlah semua barangan dahulu, baru tolak daripada bajet.", en: "Try adding up all the items first, then subtracting from the budget." },
        reflection: { ms: "Anda guna TOLAK untuk uruskan wang — kemahiran penting untuk belanjawan setiap hari!", en: "You used SUBTRACTION to manage money — an important everyday budgeting skill!" },
        generateMath: (mode) => generateBudgetSubtract(GROCERY_ITEMS, undefined, mode),
      },
      {
        image: "/missions/scenes/grocery-challenge-1.webp",
        tokens: { helper: { ms: "seorang jiran", en: "a neighbour" }, place: { ms: "kedai runcit", en: "the grocery store" } },
        intro: { ms: "Pintar teman {helper} membeli keperluan dapur di {place}.", en: "Pintar accompanies {helper} to buy kitchen supplies at {place}." },
        challenge: { ms: "Bantu kira baki wang {helper} selepas semua belian dibayar.", en: "Help work out how much money {helper} has left after paying for everything." },
        outcomeSuccess: { ms: "Belanjawan {helper} mencukupi — belian selesai dengan jayanya!", en: "{helper}'s budget was enough — the shopping is done!" },
        outcomeRetry: { ms: "Belum tepat — semak semula jumlah kos semua barangan.", en: "Not quite — recheck the total cost of all the items." },
        reflection: { ms: "Menguruskan wang bermula dengan tahu jumlah perbelanjaan sebelum menolak daripada bajet.", en: "Managing money starts with knowing the total spend before subtracting it from the budget." },
        generateMath: (mode) => generateBudgetSubtract(GROCERY_ITEMS, undefined, mode),
      },
      {
        image: "/missions/scenes/grocery-challenge-2.webp",
        tokens: { helper: { ms: "sebuah keluarga", en: "a family" }, place: { ms: "pasar raya", en: "the supermarket" } },
        intro: { ms: "Pintar menemani {helper} membeli bahan masakan untuk majlis di {place}.", en: "Pintar joins {helper} buying ingredients for a gathering at {place}." },
        challenge: { ms: "Berapakah baki wang {helper} selepas semua bahan dibeli?", en: "How much money does {helper} have left after buying all the ingredients?" },
        outcomeSuccess: { ms: "Semua bahan berjaya dibeli dalam bajet — masakan boleh bermula!", en: "All the ingredients were bought within budget — cooking can begin!" },
        outcomeRetry: { ms: "Cuba kira semula — tambah dahulu semua harga, baru tolak daripada bajet.", en: "Try again — add up all the prices first, then subtract from the budget." },
        reflection: { ms: "Menjumlahkan kos dahulu sebelum menolak ialah cara terbaik untuk elak silap.", en: "Adding up the cost first before subtracting is the best way to avoid mistakes." },
        generateMath: (mode) => generateBudgetSubtract(GROCERY_ITEMS, undefined, mode),
      },
    ],
  },
  {
    id: "leaky-water-tank",
    category: "measurement",
    kind: "builder",
    yearLevel: 4,
    title: { ms: "Tangki Air Yang Bocor", en: "The Leaky Water Tank" },
    skillTag: { ms: "Penukaran unit ukuran", en: "Unit conversion" },
    emoji: "🚰",
    rewardXp: 20,
    badgeId: "fixer",
    variants: [
      {
        image: "/missions/scenes/leaky-water-tank-0.webp",
        tokens: { place: { ms: "Kampung Air", en: "Water Village" }, thing: { ms: "tangki air", en: "water tank" } },
        intro: { ms: "Sebuah {thing} di {place} bocor. Pintar perlu tahu jumlah air yang hilang dalam unit yang lebih kecil untuk membaikinya.", en: "A {thing} in {place} is leaking. Pintar needs to know the missing amount in a smaller unit to fix it." },
        challenge: { ms: "Tukarkan ukuran yang diberikan kepada unit yang lebih kecil.", en: "Convert the given measurement into the smaller unit." },
        outcomeSuccess: { ms: "{thing} itu berjaya dibaiki dengan ukuran yang tepat!", en: "The {thing} is fixed with the exact measurement!" },
        outcomeRetry: { ms: "Ukuran itu masih tidak tepat — semak semula penukaran unit anda.", en: "The measurement still isn't right — check your unit conversion again." },
        reflection: { ms: "Menukar unit besar kepada unit kecil bermakna DARAB dengan faktor penukaran.", en: "Converting a bigger unit to a smaller one means MULTIPLYING by the conversion factor." },
        generateMath: (mode) => generateUnitConvert({ bigUnit: "L", smallUnit: "mL", factor: 1000, maxBig: 9 }, mode),
      },
      {
        image: "/missions/scenes/leaky-water-tank-1.webp",
        tokens: { place: { ms: "Gudang Bekalan", en: "Supply Depot" }, thing: { ms: "beg bekalan", en: "supply bag" } },
        intro: { ms: "Di {place}, sebuah {thing} perlu diisi semula, tetapi label hanya menunjukkan unit besar.", en: "At {place}, a {thing} needs restocking, but the label only shows the bigger unit." },
        challenge: { ms: "Tukarkan berat yang diberikan kepada unit yang lebih kecil supaya bekalan boleh diagihkan.", en: "Convert the given weight to the smaller unit so the supplies can be distributed." },
        outcomeSuccess: { ms: "Bekalan berjaya diagihkan dengan ukuran yang betul!", en: "The supplies were distributed with the correct measurement!" },
        outcomeRetry: { ms: "Cuba semak semula — ingat faktor penukaran unit itu.", en: "Try checking again — remember the unit conversion factor." },
        reflection: { ms: "1 kg = 1000 g — kemahiran ini penting setiap kali kita baca label makanan!", en: "1 kg = 1000 g — this skill matters every time we read a food label!" },
        generateMath: (mode) => generateUnitConvert({ bigUnit: "kg", smallUnit: "g", factor: 1000, maxBig: 9 }, mode),
      },
    ],
  },
  {
    id: "mysterious-angle-door",
    category: "geometry",
    kind: "mystery",
    yearLevel: 5,
    title: { ms: "Pintu Sudut Misteri", en: "The Mysterious Angle Door" },
    skillTag: { ms: "Jumlah sudut", en: "Angle sums" },
    emoji: "🚪",
    rewardXp: 25,
    badgeId: "detective",
    variants: [
      {
        image: "/missions/scenes/mysterious-angle-door-0.webp",
        tokens: { place: { ms: "Kuil Purba", en: "Ancient Temple" } },
        intro: { ms: "Sebuah pintu batu di {place} hanya akan terbuka jika kod sudut yang betul dimasukkan.", en: "A stone door in the {place} will only open if the correct angle code is entered." },
        challenge: { ms: "Cari sudut yang hilang untuk membuka pintu itu.", en: "Find the missing angle to open the door." },
        outcomeSuccess: { ms: "Pintu itu terbuka dengan bunyi berdehit — misteri selesai!", en: "The door creaks open — mystery solved!" },
        outcomeRetry: { ms: "Pintu itu masih terkunci — cuba kira semula sudut yang hilang.", en: "The door is still locked — try recalculating the missing angle." },
        reflection: { ms: "Dua sudut yang membentuk garis lurus sentiasa berjumlah 180°!", en: "Two angles that form a straight line always add up to 180°!" },
        generateMath: (mode) => generateMissingAngle([180], mode),
      },
      {
        image: "/missions/scenes/mysterious-angle-door-1.webp",
        tokens: { place: { ms: "Makmal Rahsia", en: "Secret Laboratory" } },
        intro: { ms: "Sebuah peti keselamatan di {place} dikunci dengan teka-teki sudut.", en: "A safe in the {place} is locked with an angle puzzle." },
        challenge: { ms: "Selesaikan teka-teki sudut untuk buka peti itu.", en: "Solve the angle puzzle to open the safe." },
        outcomeSuccess: { ms: "Peti itu terbuka — teka-teki berjaya diselesaikan!", en: "The safe pops open — puzzle solved!" },
        outcomeRetry: { ms: "Belum betul — cuba semula.", en: "Not quite right — try again." },
        reflection: { ms: "Sudut tepat ialah 90°, dan sudut penuh ialah 360° — ingat nombor ini!", en: "A right angle is 90°, and a full turn is 360° — remember these numbers!" },
        generateMath: (mode) => generateMissingAngle([90, 360], mode),
      },
    ],
  },
  {
    id: "village-data-puzzle",
    category: "data",
    kind: "mystery",
    yearLevel: 4,
    title: { ms: "Teka-teki Data Kampung", en: "The Village Data Puzzle" },
    skillTag: { ms: "Menjumlahkan data", en: "Totaling data" },
    emoji: "📊",
    rewardXp: 20,
    badgeId: "detective",
    variants: [
      {
        image: "/missions/scenes/village-data-puzzle-0.webp",
        tokens: { place: { ms: "Pasar Buah", en: "Fruit Market" } },
        intro: { ms: "Penjaga {place} kehilangan rekod jualan dan perlukan bantuan mengira semula.", en: "The keeper of the {place} lost the sales record and needs help recounting." },
        challenge: { ms: "Jumlahkan data yang dikumpul untuk bantu penjaga itu.", en: "Total up the data collected to help the keeper." },
        outcomeSuccess: { ms: "Rekod berjaya dikira semula — penjaga pasar sangat gembira!", en: "The record is recounted — the market keeper is thrilled!" },
        outcomeRetry: { ms: "Jumlah itu masih tidak tepat — cuba tambah semula setiap kategori.", en: "The total still isn't right — try adding up each category again." },
        reflection: { ms: "Membaca data dan menjumlahkannya ialah kemahiran penting dalam Statistik!", en: "Reading data and totaling it is an important Statistics skill!" },
        generateMath: (mode) => generateDataTotal(FRUIT_CATEGORIES, mode),
      },
    ],
  },
  {
    id: "great-train-schedule",
    category: "time",
    kind: "time_travel",
    yearLevel: 5,
    title: { ms: "Jadual Keretapi Agung", en: "The Great Train Schedule" },
    skillTag: { ms: "Tempoh masa", en: "Elapsed time" },
    emoji: "🚂",
    rewardXp: 25,
    badgeId: "time_traveler",
    variants: [
      {
        image: "/missions/scenes/great-train-schedule-0.webp",
        tokens: { place: { ms: "Stesen Nombor", en: "Number Station" } },
        intro: { ms: "Seorang penumpang di {place} perlu tahu berapa lama perjalanan keretapinya mengambil masa.", en: "A passenger at {place} needs to know how long their train journey takes." },
        challenge: { ms: "Kira tempoh masa perjalanan itu.", en: "Work out how long the journey takes." },
        outcomeSuccess: { ms: "Penumpang itu sampai tepat pada masanya — terima kasih!", en: "The passenger arrives right on time — thank you!" },
        outcomeRetry: { ms: "Belum tepat — cuba kira semula perbezaan antara masa mula dan tamat.", en: "Not quite — try recalculating the difference between the start and end times." },
        reflection: { ms: "Tempoh masa ialah PERBEZAAN antara masa tamat dan masa mula.", en: "Elapsed time is the DIFFERENCE between the end time and the start time." },
        generateMath: (mode) => generateTimeDuration([15, 30, 45, 60, 90], mode),
      },
    ],
  },
  {
    id: "pattern-detective",
    category: "kbat",
    kind: "mystery",
    yearLevel: 6,
    title: { ms: "Detektif Corak", en: "Pattern Detective" },
    skillTag: { ms: "Corak & penaakulan", en: "Patterns & reasoning" },
    emoji: "🕵️",
    rewardXp: 30,
    badgeId: "detective",
    variants: [
      {
        image: "/missions/scenes/pattern-detective-0.webp",
        tokens: { place: { ms: "Perpustakaan Purba", en: "Ancient Library" } },
        intro: { ms: "Sebuah buku nota lama di {place} mengandungi corak nombor rahsia.", en: "An old notebook in the {place} holds a secret number pattern." },
        challenge: { ms: "Cari nombor seterusnya dalam corak itu untuk mendedahkan rahsianya.", en: "Find the next number in the pattern to reveal the secret." },
        outcomeSuccess: { ms: "Corak itu berjaya didedahkan — rahsia terungkai!", en: "The pattern is revealed — the secret is solved!" },
        outcomeRetry: { ms: "Belum tepat — perhatikan berapa banyak setiap nombor bertambah.", en: "Not quite — look carefully at how much each number increases by." },
        reflection: { ms: "Mencari corak bermakna kenal pasti PERATURAN yang berulang pada setiap langkah.", en: "Finding a pattern means spotting the RULE that repeats at every step." },
        generateMath: (mode) => generatePatternMissing(mode),
      },
    ],
  },
  {
    id: "school-trip-planning",
    category: "real_life",
    kind: "financial_literacy",
    yearLevel: 5,
    title: { ms: "Perancangan Lawatan Sekolah", en: "School Trip Planning" },
    skillTag: { ms: "Belanjawan kehidupan sebenar", en: "Real-life budgeting" },
    emoji: "🏕️",
    rewardXp: 30,
    badgeId: "fixer",
    variants: [
      {
        image: "/missions/scenes/school-trip-planning-0.webp",
        tokens: { place: { ms: "Tapak Perkhemahan", en: "Campsite" } },
        intro: { ms: "Sekumpulan pelajar merancang lawatan berkhemah ke {place} dan perlukan bantuan menguruskan belanjawan.", en: "A group of students is planning a camping trip to the {place} and needs help managing the budget." },
        challenge: { ms: "Kira baki belanjawan selepas semua barangan perkhemahan dibeli.", en: "Work out the remaining budget after all the camping items are bought." },
        outcomeSuccess: { ms: "Lawatan berkhemah itu bersedia — belanjawan diuruskan dengan bijak!", en: "The camping trip is ready — the budget was managed wisely!" },
        outcomeRetry: { ms: "Cuba kira semula jumlah kos semua barangan dahulu.", en: "Try adding up the total cost of all the items first." },
        reflection: { ms: "Merancang belanjawan bermakna tahu had perbelanjaan SEBELUM membeli.", en: "Budget planning means knowing your spending limit BEFORE you buy." },
        generateMath: (mode) => generateBudgetSubtract(CAMPING_ITEMS, [40, 50, 60, 70], mode),
      },
    ],
  },
  {
    id: "treasure-cave",
    category: "number",
    kind: "exploration",
    yearLevel: 4,
    title: { ms: "Gua Harta Karun", en: "The Treasure Cave" },
    skillTag: { ms: "Pendaraban", en: "Multiplication" },
    emoji: "💎",
    rewardXp: 20,
    badgeId: "kindness",
    variants: [
      {
        image: "/missions/scenes/treasure-cave-0.webp",
        tokens: { place: { ms: "Gua Berkilauan", en: "Glittering Cave" }, item: { ms: "permata", en: "gems" } },
        intro: { ms: "Pintar menjumpai laluan tersembunyi menuju {place}, penuh dengan peti harta karun.", en: "Pintar discovers a hidden path leading into the {place}, full of treasure chests." },
        challenge: { ms: "Setiap peti mengandungi bilangan {item} yang sama. Kira jumlah {item} yang ditemui.", en: "Each chest holds the same number of {item}. Work out the total {item} found." },
        outcomeSuccess: { ms: "Semua {item} berjaya dikira — kawasan baharu {place} kini diterokai!", en: "All the {item} are counted — a new part of the {place} is now explored!" },
        outcomeRetry: { ms: "Bilangan itu masih tidak tepat — cuba kira semula kumpulan itu.", en: "That number isn't quite right — try recounting the groups." },
        reflection: { ms: "Mengira kumpulan yang sama saiz bermakna DARAB — cara pantas untuk mengira secara berulang!", en: "Counting equal-sized groups is MULTIPLICATION — a fast way to count repeatedly!" },
        generateMath: (mode) => generateMultiply(9, mode),
      },
      {
        image: "/missions/scenes/treasure-cave-1.webp",
        tokens: { place: { ms: "Terowong Bawah Tanah", en: "Underground Tunnels" }, item: { ms: "syiling emas", en: "gold coins" } },
        intro: { ms: "Jauh di dalam {place}, Pintar menemui beberapa beg berisi harta yang belum dikira.", en: "Deep inside the {place}, Pintar finds several bags of uncounted treasure." },
        challenge: { ms: "Setiap beg mempunyai bilangan {item} yang sama. Bantu Pintar kira jumlah keseluruhan.", en: "Each bag has the same number of {item}. Help Pintar work out the grand total." },
        outcomeSuccess: { ms: "Harta karun berjaya dikira — pengembaraan diteruskan lebih dalam!", en: "The treasure is counted — the adventure continues deeper!" },
        outcomeRetry: { ms: "Cuba kira semula — pastikan setiap beg dikira dengan betul.", en: "Try again — make sure each bag is counted correctly." },
        reflection: { ms: "Pendaraban menjimatkan masa berbanding mengira satu demi satu!", en: "Multiplication saves time compared to counting one by one!" },
        generateMath: (mode) => generateMultiply(12, mode),
      },
    ],
  },
  {
    id: "potion-ingredients",
    category: "fraction",
    kind: "mystery",
    yearLevel: 5,
    title: { ms: "Bahan Ramuan Ajaib", en: "Potion Ingredients" },
    skillTag: { ms: "Tambah pecahan (penyebut sama)", en: "Fraction addition (same denominator)" },
    emoji: "🧪",
    rewardXp: 25,
    badgeId: "bridge_builder",
    variants: [
      {
        image: "/missions/scenes/potion-ingredients-0.webp",
        tokens: { place: { ms: "Menara Ahli Sihir", en: "Wizard's Tower" }, thing: { ms: "cecair ajaib", en: "magic liquid" } },
        intro: { ms: "Seorang ahli sihir di {place} sedang mencampur {thing} untuk ramuan penting.", en: "A wizard in the {place} is mixing {thing} for an important potion." },
        challenge: { ms: "Gabungkan dua ukuran {thing} untuk dapatkan jumlah yang betul.", en: "Combine two measures of {thing} to get the correct total." },
        outcomeSuccess: { ms: "Ramuan itu sempurna — {thing} bercampur dengan tepat!", en: "The potion is perfect — the {thing} combined exactly right!" },
        outcomeRetry: { ms: "Ramuan itu belum tepat — cuba tambah semula kedua-dua pecahan itu.", en: "The potion isn't quite right — try adding the two fractions again." },
        reflection: { ms: "Menambah pecahan berpenyebut sama bermakna kita tambah sahaja PENGANGKA.", en: "Adding same-denominator fractions means we just add the NUMERATORS." },
        generateMath: (mode) => generateFractionAdd([4, 6, 8], mode),
      },
    ],
  },
  {
    id: "market-bargain",
    category: "money",
    kind: "rescue",
    yearLevel: 4,
    title: { ms: "Tawar-menawar Pasar", en: "Market Bargain" },
    skillTag: { ms: "Wang & tolak berbilang item", en: "Money & multi-item subtraction" },
    emoji: "🎈",
    rewardXp: 20,
    badgeId: "money_hero",
    variants: [
      {
        image: "/missions/scenes/market-bargain-0.webp",
        tokens: { child: { ms: "seorang kanak-kanak", en: "a child" }, place: { ms: "pasar malam", en: "the night market" } },
        intro: { ms: "Pintar bertemu {child} yang ingin membeli mainan di {place} dengan wang saku yang terhad.", en: "Pintar meets {child} who wants to buy toys at {place} with limited pocket money." },
        challenge: { ms: "Bantu kira baki wang selepas mainan-mainan itu dibeli.", en: "Help work out the money left after the toys are bought." },
        outcomeSuccess: { ms: "{child} pulang dengan gembira, membawa mainan dan baki wang!", en: "{child} goes home happy, with toys and money to spare!" },
        outcomeRetry: { ms: "Cuba kira semula jumlah harga semua mainan dahulu.", en: "Try adding up the total price of all the toys first." },
        reflection: { ms: "Menyemak baki wang sebelum berbelanja lagi ialah tabiat kewangan yang baik!", en: "Checking your remaining money before spending more is a good money habit!" },
        generateMath: (mode) => generateBudgetSubtract(TOY_MARKET_ITEMS, [30, 40, 50], mode),
      },
    ],
  },
  {
    id: "fence-the-garden",
    category: "geometry",
    kind: "builder",
    yearLevel: 4,
    title: { ms: "Pagar Taman", en: "Fence the Garden" },
    skillTag: { ms: "Perimeter segi empat tepat", en: "Perimeter of a rectangle" },
    emoji: "🌻",
    rewardXp: 20,
    badgeId: "fixer",
    variants: [
      {
        image: "/missions/scenes/fence-the-garden-0.webp",
        tokens: { place: { ms: "Taman Bunga", en: "Flower Garden" } },
        intro: { ms: "Sebuah {place} perlu dipagari sebelum musim tengkujuh tiba.", en: "A {place} needs fencing before the rainy season arrives." },
        challenge: { ms: "Kira jumlah panjang pagar yang diperlukan untuk mengelilingi taman itu.", en: "Work out the total length of fencing needed to go around the garden." },
        outcomeSuccess: { ms: "Pagar telah siap dibina — bunga-bunga kini selamat!", en: "The fence is built — the flowers are now safe!" },
        outcomeRetry: { ms: "Pagar itu masih tidak cukup panjang — cuba kira semula perimeter taman.", en: "The fence still isn't long enough — try recalculating the garden's perimeter." },
        reflection: { ms: "Perimeter ialah jumlah SEMUA sisi sesuatu bentuk.", en: "Perimeter is the total of ALL the sides of a shape." },
        generateMath: (mode) => generatePerimeter(20, mode),
      },
    ],
  },
  {
    id: "weather-watcher",
    category: "data",
    kind: "exploration",
    yearLevel: 4,
    title: { ms: "Pemerhati Cuaca", en: "Weather Watcher" },
    skillTag: { ms: "Menjumlahkan data", en: "Totaling data" },
    emoji: "🌦️",
    rewardXp: 20,
    badgeId: "detective",
    variants: [
      {
        image: "/missions/scenes/weather-watcher-0.webp",
        tokens: { place: { ms: "Stesen Cuaca", en: "Weather Station" } },
        intro: { ms: "Pintar meneroka {place} dan menjumpai rekod cuaca sebulan yang belum dijumlahkan.", en: "Pintar explores the {place} and finds a month's weather record that hasn't been totaled." },
        challenge: { ms: "Jumlahkan data cuaca yang dikumpul.", en: "Total up the weather data collected." },
        outcomeSuccess: { ms: "Rekod cuaca berjaya dijumlahkan — laporan sedia untuk dihantar!", en: "The weather record is totaled — the report is ready to send!" },
        outcomeRetry: { ms: "Jumlah itu masih tidak tepat — cuba tambah semula setiap kategori.", en: "The total still isn't right — try adding up each category again." },
        reflection: { ms: "Mengumpul dan menjumlahkan data membantu kita fahami corak cuaca dari semasa ke semasa.", en: "Collecting and totaling data helps us understand weather patterns over time." },
        generateMath: (mode) => generateDataTotal(WEATHER_CATEGORIES, mode),
      },
    ],
  },
  {
    id: "festival-countdown",
    category: "time",
    kind: "time_travel",
    yearLevel: 4,
    title: { ms: "Detik Menuju Perayaan", en: "Festival Countdown" },
    skillTag: { ms: "Tempoh masa", en: "Elapsed time" },
    emoji: "🎆",
    rewardXp: 20,
    badgeId: "time_traveler",
    variants: [
      {
        image: "/missions/scenes/festival-countdown-0.webp",
        tokens: { place: { ms: "Dataran Perayaan", en: "Festival Square" } },
        intro: { ms: "Persiapan sedang berjalan di {place} sebelum perayaan besar bermula.", en: "Preparations are underway at the {place} before the big festival begins." },
        challenge: { ms: "Kira berapa lama masa persediaan itu mengambil masa.", en: "Work out how long the preparation takes." },
        outcomeSuccess: { ms: "Persediaan selesai tepat pada masanya — perayaan boleh bermula!", en: "Preparations finish right on time — the festival can begin!" },
        outcomeRetry: { ms: "Belum tepat — cuba kira semula perbezaan antara masa mula dan tamat.", en: "Not quite — try recalculating the difference between the start and end times." },
        reflection: { ms: "Merancang tempoh masa membantu kita bersedia lebih awal!", en: "Planning elapsed time helps us get ready ahead of schedule!" },
        generateMath: (mode) => generateTimeDuration([30, 45, 60, 90, 120], mode),
      },
    ],
  },
  {
    id: "number-riddle",
    category: "kbat",
    kind: "mystery",
    yearLevel: 6,
    title: { ms: "Teka-teki Nombor", en: "Number Riddle" },
    skillTag: { ms: "Penaakulan & faktor", en: "Reasoning & factors" },
    emoji: "🧩",
    rewardXp: 30,
    badgeId: "detective",
    variants: [
      {
        image: "/missions/scenes/number-riddle-0.webp",
        tokens: { place: { ms: "Bilik Rahsia", en: "Secret Room" } },
        intro: { ms: "Sebuah gulungan kertas tua di {place} mengandungi teka-teki nombor yang belum diselesaikan.", en: "An old scroll in the {place} holds an unsolved number riddle." },
        challenge: { ms: "Selesaikan teka-teki itu untuk mendedahkan nombor rahsia.", en: "Solve the riddle to reveal the secret number." },
        outcomeSuccess: { ms: "Teka-teki berjaya diselesaikan — rahsia terungkai sepenuhnya!", en: "The riddle is solved — the secret is fully revealed!" },
        outcomeRetry: { ms: "Belum tepat — cuba fikirkan nombor apa yang perlu didarab untuk dapatkan jawapan itu.", en: "Not quite — think about what number needs to be multiplied to get that answer." },
        reflection: { ms: "Mencari nombor yang hilang dalam pendaraban ialah kebalikan daripada membahagi!", en: "Finding a missing factor in multiplication is the reverse of dividing!" },
        generateMath: (mode) => generateMissingFactor(12, mode),
      },
    ],
  },
  {
    id: "family-budget-planner",
    category: "real_life",
    kind: "financial_literacy",
    yearLevel: 6,
    title: { ms: "Perancang Belanjawan Keluarga", en: "Family Budget Planner" },
    skillTag: { ms: "Belanjawan kehidupan sebenar", en: "Real-life budgeting" },
    emoji: "🏠",
    rewardXp: 30,
    badgeId: "fixer",
    variants: [
      {
        image: "/missions/scenes/family-budget-planner-0.webp",
        tokens: { place: { ms: "rumah keluarga", en: "family home" } },
        intro: { ms: "Sebuah keluarga di {place} perlu menguruskan bil bulanan mereka dengan bijak.", en: "A family at the {place} needs to manage their monthly bills wisely." },
        challenge: { ms: "Kira baki belanjawan selepas semua bil bulanan dibayar.", en: "Work out the remaining budget after all the monthly bills are paid." },
        outcomeSuccess: { ms: "Semua bil berjaya dibayar dengan belanjawan yang mencukupi!", en: "All the bills are paid, within budget!" },
        outcomeRetry: { ms: "Cuba kira semula jumlah kesemua bil dahulu.", en: "Try adding up the total of all the bills first." },
        reflection: { ms: "Menguruskan belanjawan keluarga bermakna tahu jumlah perbelanjaan SEBELUM ia melebihi pendapatan.", en: "Managing a family budget means knowing total spending BEFORE it exceeds income." },
        generateMath: (mode) => generateBudgetSubtract(HOUSEHOLD_BILLS, [150, 180, 200, 220], mode),
      },
    ],
  },
  {
    id: "merchants-bargain",
    category: "money",
    kind: "financial_literacy",
    yearLevel: 6,
    title: { ms: "Tawaran Saudagar", en: "The Merchant's Bargain" },
    skillTag: { ms: "Diskaun, jumlah, dan baki — pelbagai langkah", en: "Discount, total, and change — multi-step" },
    emoji: "🏺",
    rewardXp: 35,
    badgeId: "money_hero",
    variants: [
      {
        image: "/missions/scenes/merchants-bargain-0.webp",
        tokens: { place: { ms: "Pasar Saudagar", en: "Merchant's Bazaar" } },
        intro: { ms: "Seorang saudagar di {place} menawarkan diskaun istimewa hari ini, tetapi pengiraannya rumit.", en: "A merchant at the {place} is offering a special discount today, but the calculation is tricky." },
        challenge: { ms: "Berapakah baki wang yang akan diterima selepas belian dan bayaran ini?", en: "How much change will be received after this purchase and payment?" },
        outcomeSuccess: { ms: "Saudagar itu kagum — semua langkah dikira dengan tepat!", en: "The merchant is impressed — every step was worked out correctly!" },
        outcomeRetry: { ms: "Belum tepat — fikirkan apa yang perlu dikira DAHULU sebelum mencari baki.", en: "Not quite — think about what needs to be worked out FIRST before finding the change." },
        reflection: { ms: "Soalan pelbagai langkah perlu diselesaikan SATU LANGKAH pada satu masa, secara tersusun.", en: "Multi-step problems need to be solved ONE STEP at a time, in order." },
        generateMath: () => generateMultiStepBudgetDiscount(MERCHANT_GOODS),
      },
    ],
  },
  {
    id: "recipe-scaling",
    category: "fraction",
    kind: "builder",
    yearLevel: 6,
    title: { ms: "Skala Resipi", en: "Recipe Scaling" },
    skillTag: { ms: "Tambah dan darab pecahan — pelbagai langkah", en: "Fraction addition and multiplication — multi-step" },
    emoji: "👨‍🍳",
    rewardXp: 35,
    badgeId: "bridge_builder",
    variants: [
      {
        image: "/missions/scenes/recipe-scaling-0.webp",
        tokens: { place: { ms: "Dapur Besar", en: "Grand Kitchen" }, thing: { ms: "adunan istimewa", en: "special batter" } },
        intro: { ms: "Seorang tukang masak di {place} perlu menyediakan {thing} untuk ramai tetamu.", en: "A chef at the {place} needs to prepare {thing} for many guests." },
        challenge: { ms: "Berapakah jumlah bahan yang diperlukan untuk menyediakan {thing} bagi semua tetamu?", en: "How much of the ingredient is needed to prepare the {thing} for all the guests?" },
        outcomeSuccess: { ms: "Resipi berjaya diskalakan dengan tepat — semua tetamu akan kenyang!", en: "The recipe is scaled perfectly — every guest will be well fed!" },
        outcomeRetry: { ms: "Belum tepat — fikirkan berapa banyak diperlukan untuk SATU unit dahulu.", en: "Not quite — think about how much is needed for ONE unit first." },
        reflection: { ms: "Menskalakan resipi ialah kemahiran sebenar tukang masak — tambah dahulu, darab kemudian!", en: "Scaling a recipe is a real chef's skill — add first, then multiply!" },
        generateMath: () => generateMultiStepFractionScale(),
      },
    ],
  },
  {
    id: "the-great-leak",
    category: "measurement",
    kind: "mystery",
    yearLevel: 6,
    title: { ms: "Kebocoran Besar", en: "The Great Leak" },
    skillTag: { ms: "Penukaran unit dan tolak — pelbagai langkah", en: "Unit conversion and subtraction — multi-step" },
    emoji: "🕳️",
    rewardXp: 35,
    badgeId: "fixer",
    variants: [
      {
        image: "/missions/scenes/the-great-leak-0.webp",
        tokens: { place: { ms: "Loji Air Purba", en: "Ancient Waterworks" }, thing: { ms: "air", en: "water" } },
        intro: { ms: "Sebuah loji {thing} purba di {place} kehilangan bekalan secara misteri.", en: "An ancient {thing} works at {place} is mysteriously losing supply." },
        challenge: { ms: "Berapakah baki bekalan {thing} yang tinggal sekarang?", en: "How much {thing} supply is left now?" },
        outcomeSuccess: { ms: "Misteri kebocoran selesai — baki bekalan berjaya dikira dengan tepat!", en: "The leak mystery is solved — the remaining supply was worked out exactly!" },
        outcomeRetry: { ms: "Belum tepat — pastikan kedua-dua jumlah menggunakan unit yang SAMA sebelum ditolak.", en: "Not quite — make sure both amounts use the SAME unit before subtracting." },
        reflection: { ms: "Apabila unit berbeza terlibat, tukar kepada unit yang SAMA dahulu sebelum mengira selanjutnya.", en: "When different units are involved, convert to the SAME unit first before calculating further." },
        generateMath: () => generateMultiStepUnitSubtract({ bigUnit: "L", smallUnit: "mL", factor: 1000, maxBig: 18 }),
      },
    ],
  },
];

export function getMissionById(id: string): MissionTemplate | undefined {
  return MISSIONS.find((m) => m.id === id);
}
